services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: myblog-server
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://myblog:myblog@db:5432/myblog
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: myblog-db
    environment:
      - POSTGRES_USER=myblog
      - POSTGRES_PASSWORD=myblog
      - POSTGRES_DB=myblog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myblog -d myblog"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
